// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCho986QoIGJeQ_bn1rGM8Xii7VV5tOtRI',
    appId: '1:150195290547:web:fe80fd460adeb175ec0bc6',
    messagingSenderId: '150195290547',
    projectId: 'groupalarm-6f8f2',
    authDomain: 'groupalarm-6f8f2.firebaseapp.com',
    storageBucket: 'groupalarm-6f8f2.appspot.com',
    measurementId: 'G-5LCGG167SP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUjle6V4LDhRVAp_AFGYSTfi6a7jfLuaw',
    appId: '1:150195290547:android:6118d665193980b1ec0bc6',
    messagingSenderId: '150195290547',
    projectId: 'groupalarm-6f8f2',
    storageBucket: 'groupalarm-6f8f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgraiXsSDvUDCy7Zt8dJg1pdWxmCy9hzM',
    appId: '1:150195290547:ios:93bd1fc52a200b19ec0bc6',
    messagingSenderId: '150195290547',
    projectId: 'groupalarm-6f8f2',
    storageBucket: 'groupalarm-6f8f2.appspot.com',
    iosClientId: '150195290547-tdtm54drdki524478tl07msu6bnmtmit.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgraiXsSDvUDCy7Zt8dJg1pdWxmCy9hzM',
    appId: '1:150195290547:ios:93bd1fc52a200b19ec0bc6',
    messagingSenderId: '150195290547',
    projectId: 'groupalarm-6f8f2',
    storageBucket: 'groupalarm-6f8f2.appspot.com',
    iosClientId: '150195290547-tdtm54drdki524478tl07msu6bnmtmit.apps.googleusercontent.com',
    iosBundleId: 'com.example.alarmApp',
  );
}
